package metadata

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestOrdinaryCommentIsNotAHeader is the regression this file exists for. Every
// "<!-- word: text -->" parses as a header comment, so refusing an unrecognised
// header meant refusing the document over a note the author left themselves.
// TODO:, Author: and SPDX-License-Identifier: are in every second repository,
// and a document carrying one stopped publishing at all.
func TestOrdinaryCommentIsNotAHeader(t *testing.T) {
	comments := []string{
		"TODO: rewrite this page",
		"Generated by: docgen v2",
		"SPDX-License-Identifier: MIT",
		"vim: set ft=markdown",
		"NOTE: the numbers below are estimates",
	}

	for _, comment := range comments {
		t.Run(comment, func(t *testing.T) {
			meta, body, err := extract(t, "<!-- Space: DOCS -->\n<!-- Title: Doc -->\n<!-- "+
				comment+" -->\n\nBody.\n")

			require.NoError(t, err)
			require.NotNil(t, meta)

			assert.Equal(t, "Doc", meta.Title, "the headers around it still apply")
			assert.Contains(t, body, comment,
				"the comment belongs to the document and stays in it")
		})
	}
}

// TestCommentAmongHeadersDoesNotStrandThemBelowIt: a comment that ended the
// header run would take every header after it out of scope -- the same failure
// a blank line used to cause, arriving by a different route.
func TestCommentAmongHeadersDoesNotStrandThemBelowIt(t *testing.T) {
	meta, _, err := extract(t, `<!-- Space: DOCS -->
<!-- TODO: rewrite -->
<!-- Title: Still Applied -->
<!-- Label: important -->

Body.
`)

	require.NoError(t, err)
	require.NotNil(t, meta)

	assert.Equal(t, "Still Applied", meta.Title)
	assert.Equal(t, "DOCS", meta.Space)
	assert.Equal(t, []string{"important"}, meta.Labels)
}

// TestCommentAboveHeadersLeavesThemAlone covers the other placement: a comment
// written before any header must not make the block look like something other
// than the header block.
func TestCommentAboveHeadersLeavesThemAlone(t *testing.T) {
	meta, _, err := extract(t, "<!-- Generated by: docgen -->\n<!-- Space: DOCS -->\n"+
		"<!-- Title: Above -->\n\nBody.\n")

	require.NoError(t, err)
	require.NotNil(t, meta)
	assert.Equal(t, "Above", meta.Title)
}

// TestMisspelledHeaderIsStillRefused: the point of refusing an unknown header
// was that a typo silently changed what was published -- the line is taken out
// of the body either way, so the page went up without whatever it asked for and
// the run still exited zero. That has to survive being made lenient about
// ordinary comments.
func TestMisspelledHeaderIsStillRefused(t *testing.T) {
	typos := map[string]string{
		"Titel":  "Title", // transposed
		"Titl":   "Title", // dropped
		"Titles": "Title", // added
		"Spce":   "Space",
		"Labe":   "Label",
	}

	for typo, meant := range typos {
		t.Run(typo, func(t *testing.T) {
			_, _, err := extract(t, "<!-- Space: DOCS -->\n<!-- "+typo+": x -->\n\nBody.\n")

			require.Error(t, err)
			assert.Contains(t, err.Error(), typo, "the message quotes what was written")
			assert.Contains(t, err.Error(), meant, "and what was probably meant")
		})
	}
}

// TestHeaderNamesAreMatchedWithoutCase pins what canonicalHeader replaced: the
// old code title-cased the key, which is how any comment became a header name.
// Matching against the list has to keep accepting the spellings documents use.
func TestHeaderNamesAreMatchedWithoutCase(t *testing.T) {
	meta, _, err := extract(t, "<!-- space: DOCS -->\n<!-- TITLE: Shouted -->\n\nBody.\n")

	require.NoError(t, err)
	require.NotNil(t, meta)
	assert.Equal(t, "DOCS", meta.Space)
	assert.Equal(t, "Shouted", meta.Title)
}

// TestEditDistanceWithinOne covers the predicate that tells a typo from a
// comment, since getting it wrong in either direction is a bug people notice:
// too tight and "Titel" publishes silently, too loose and "Note" is refused as
// a misspelling of "Order".
func TestEditDistanceWithinOne(t *testing.T) {
	within := [][2]string{
		{"Title", "Title"},
		{"Titel", "Title"},
		{"Titl", "Title"},
		{"Titles", "Title"},
		{"title", "Title"},
	}
	for _, pair := range within {
		assert.True(t, editDistanceWithinOne(pair[0], pair[1]), "%q ~ %q", pair[0], pair[1])
	}

	apart := [][2]string{
		{"TODO", "Title"},
		{"Note", "Order"},
		{"Author", "Layout"},
		{"Generated By", "Title"},
		{"SPDX-License-Identifier", "Space"},
		{"", "Title"},
	}
	for _, pair := range apart {
		assert.False(t, editDistanceWithinOne(pair[0], pair[1]), "%q !~ %q", pair[0], pair[1])
	}
}

// TestStrandedHeaderWarningSkipsCodeBlocks: a header shown inside a fence is an
// example of the syntax, which is how every document about mark writes one --
// this repository's README included. Warning about those buries the real ones.
func TestStrandedHeaderWarningSkipsCodeBlocks(t *testing.T) {
	_, body, err := extract(t, "<!-- Space: DOCS -->\n<!-- Title: Doc -->\n\n"+
		"```markdown\n<!-- Space: EXAMPLE -->\n```\n")
	require.NoError(t, err)

	// warnStrandedHeaders only logs, so the assertion is on what it inspects:
	// the fenced line must be inside a region CodeRegions reports.
	regions := CodeRegions([]byte(body))
	index := strings.Index(body, "<!-- Space: EXAMPLE -->")
	require.GreaterOrEqual(t, index, 0)

	assert.True(t, InCode(regions, index),
		"the example must be seen as code, not as a stranded header")
}

// TestLayoutMarkersAreNotHeaders covers the documented spelling of a custom
// layout, whose markers sit directly below "<!-- Layout: plain -->".
//
// parseHeaderComment cuts at the first colon, so "<!-- ac:layout-section
// type:single -->" arrives here as the key "ac" -- a header-shaped line by
// accident. The whole ac: namespace is storage markup or mark's own region
// markers, never metadata.
func TestLayoutMarkersAreNotHeaders(t *testing.T) {
	meta, body, err := extract(t, `<!-- Space: TEST -->
<!-- Title: Custom Layout -->
<!-- Layout: plain -->
<!-- ac:layout -->

<!-- ac:layout-section type:single -->
<!-- ac:layout-cell -->
Still More Content
<!-- ac:layout-cell end -->
<!-- ac:layout-section end -->

<!-- ac:layout end -->
`)
	require.NoError(t, err)
	require.NotNil(t, meta)

	assert.Equal(t, "Custom Layout", meta.Title)
	assert.Equal(t, "plain", meta.Layout)

	// The markers belong to the layout transformer, so they have to survive the
	// cut that takes the headers out -- and stay in the order they were written.
	assert.Contains(t, body, "<!-- ac:layout -->")
	assert.Contains(t, body, "<!-- ac:layout-cell -->")
	assert.Contains(t, body, "<!-- ac:layout end -->")
	assert.NotContains(t, body, "<!-- Title:")
	assert.NotContains(t, body, "<!-- Layout:")
}

// TestMacroDirectiveAmongHeadersIsKept covers the other comment that shares the
// header shape. The multi-line form survived the regression by accident -- its
// continuation lines do not parse as headers, so the run ended before the error
// -- which left the single-line form failing while the block form worked.
func TestMacroDirectiveAmongHeadersIsKept(t *testing.T) {
	block, body, err := extract(t, `<!-- Space: TEST -->
<!-- Title: With Macro -->
<!-- Macro: :draft:
     Template: ac:status
     Title: DRAFT
-->

Body :draft:
`)
	require.NoError(t, err)
	require.NotNil(t, block)

	// The page's own Title, not the one inside the macro body.
	assert.Equal(t, "With Macro", block.Title)
	assert.Contains(t, body, "<!-- Macro: :draft:")
	assert.NotContains(t, body, "<!-- Title: With Macro")

	single, singleBody, err := extract(t, `<!-- Space: TEST -->
<!-- Title: One Line Macro -->
<!-- Macro: foo -->

Body.
`)
	require.NoError(t, err)
	require.NotNil(t, single)
	assert.Equal(t, "One Line Macro", single.Title)
	assert.Contains(t, singleBody, "<!-- Macro: foo -->")
}

// TestIgnoreMarkersAreNotHeaders covers the rest of the ac: namespace.
func TestIgnoreMarkersAreNotHeaders(t *testing.T) {
	meta, body, err := extract(t, `<!-- Space: TEST -->
<!-- Title: Ignored Region -->
<!-- ac:ignore -->
Not published.
<!-- ac:ignore end -->

Body.
`)
	require.NoError(t, err)
	require.NotNil(t, meta)

	assert.Equal(t, "Ignored Region", meta.Title)
	assert.Contains(t, body, "<!-- ac:ignore -->")
}

// TestTypoIsStillRefusedBesideADirective pins that being lenient about
// directives did not weaken the check that catches a misspelling.
func TestTypoIsStillRefusedBesideADirective(t *testing.T) {
	_, _, err := extract(t, `<!-- Space: TEST -->
<!-- Titel: misspelled -->
<!-- ac:layout -->

Body.
`)
	require.Error(t, err)
	assert.Contains(t, err.Error(), `unknown header "Titel"`)
}
